#!/usr/bin/env bash
# This script installs and configures ngix
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Ngnix HTTP'
echo "Hello World!" > sudo tee /var/www/html/index.html
service nginx start
